WITH adm2021 AS (
    SELECT *
    FROM {{ source('bronze', 'adm2021') }}
),

adm2021_renamed AS (
    SELECT
        CAST(2021 AS INTEGER) AS "YEAR",
        CAST("UNITID" AS INTEGER) AS "UNITID",

        -- Applicants
        CAST("APPLCN" AS INTEGER) AS "APPLCN",
        CAST("APPLCNM" AS INTEGER) AS "APPLCNM",
        CAST("APPLCNW" AS INTEGER) AS "APPLCNW",
        CAST(NULL AS INTEGER) AS "APPLCNAN", 
        CAST(NULL AS INTEGER) AS "APPLCNUN",

        -- Admissions
        CAST("ADMSSN" AS INTEGER) AS "ADMSSN",
        CAST("ADMSSNM" AS INTEGER) AS "ADMSSNM",
        CAST("ADMSSNW" AS INTEGER) AS "ADMSSNW",
        CAST(NULL AS INTEGER) AS "ADMSSNAN",
        CAST(NULL AS INTEGER) AS "ADMSSNUN",

        -- Enrolled total
        CAST("ENRLT" AS INTEGER) AS "ENRLT",
        CAST("ENRLM" AS INTEGER) AS "ENRLM",
        CAST("ENRLW" AS INTEGER) AS "ENRLW",
        CAST(NULL AS INTEGER) AS "ENRLAN",
        CAST(NULL AS INTEGER) AS "ENRLUN",

        -- Enrolled full-time
        CAST("ENRLFT" AS INTEGER) AS "ENRLFT",
        CAST("ENRLFTM" AS INTEGER) AS "ENRLFTM",
        CAST("ENRLFTW" AS INTEGER) AS "ENRLFTW",
        CAST(NULL AS INTEGER) AS "ENRLFTAN",
        CAST(NULL AS INTEGER) AS "ENRLFTUN",

        -- Enrolled part-time
        CAST("ENRLPT" AS INTEGER) AS "ENRLPT",
        CAST("ENRLPTM" AS INTEGER) AS "ENRLPTM",
        CAST("ENRLPTW" AS INTEGER) AS "ENRLPTW",
        CAST(NULL AS INTEGER) AS "ENRLPTAN",
        CAST(NULL AS INTEGER) AS "ENRLPTUN",

        -- Test scores
        CAST("SATNUM" AS INTEGER) AS "SATNUM",
        CAST("SATPCT" AS INTEGER) AS "SATPCT",
        CAST("SATVR25" AS INTEGER) AS "SATVR25",
        CAST(NULL AS INTEGER) AS "SATVR50",
        CAST("SATVR75" AS INTEGER) AS "SATVR75",
        CAST("SATMT25" AS INTEGER) AS "SATMT25",
        CAST(NULL AS INTEGER) AS "SATMT50",
        CAST("SATMT75" AS INTEGER) AS "SATMT75",
        CAST("ACTNUM" AS INTEGER) AS "ACTNUM",
        CAST("ACTPCT" AS INTEGER) AS "ACTPCT",
        CAST("ACTCM25" AS INTEGER) AS "ACTCM25",
        CAST(NULL AS INTEGER) AS "ACTCM50",
        CAST("ACTCM75" AS INTEGER) AS "ACTCM75",
        CAST("ACTEN25" AS INTEGER) AS "ACTEN25",
        CAST(NULL AS INTEGER) AS "ACTEN50",
        CAST("ACTEN75" AS INTEGER) AS "ACTEN75",
        CAST("ACTMT25" AS INTEGER) AS "ACTMT25",
        CAST(NULL AS INTEGER) AS "ACTMT50",
        CAST("ACTMT75" AS INTEGER) AS "ACTMT75"
    FROM adm2021
)

SELECT * FROM adm2021_renamed
